export const validContact = {
  name: 'Jane Tester',
  email: 'jane.tester@example.com',
  phone: '07700900123',
  subject: 'Playwright portfolio test',
  description: 'This is an automated test message generated by the Playwright test suite.',
};

export const invalidContacts = [
  {
    label: 'missing name',
    data: { name: '', email: 'jane@example.com', phone: '07700900123', subject: 'Test', description: 'Some description here that is long enough' },
  },
  {
    label: 'invalid email',
    data: { name: 'Jane', email: 'not-an-email', phone: '07700900123', subject: 'Test', description: 'Some description here that is long enough' },
  },
  {
    label: 'short description',
    data: { name: 'Jane', email: 'jane@example.com', phone: '07700900123', subject: 'Test', description: 'Short' },
  },
];
